# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anonalog_server/log_methods_pb2/log_methods.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'anonalog_server/log_methods_pb2/log_methods.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1anonalog_server/log_methods_pb2/log_methods.proto\x12\x0blog_methods\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"Q\n\x14StoreUserDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0b\n\x03\x62io\x18\x04 \x01(\t\"m\n\x18\x43hatbotInitializeRequest\x12\x10\n\x08user_bio\x18\x01 \x01(\t\x12\x19\n\x11selected_scenario\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x12\n\nchatbot_id\x18\x04 \x01(\t\"K\n\x12\x43hatbotSendRequest\x12\x12\n\nchatbot_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x01(\t\"\x8d\x01\n\x17\x45thicsEngineSendRequest\x12\x12\n\nchatbot_id\x18\x01 \x01(\t\x12\x12\n\nbackground\x18\x02 \x01(\t\x12\x0f\n\x07\x64ilemma\x18\x03 \x01(\t\x12\x0f\n\x07options\x18\x04 \x01(\t\x12\x16\n\x0e\x64\x65sired_result\x18\x05 \x01(\t\x12\x10\n\x08response\x18\x06 \x01(\t\"4\n\x10StandardResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xee\x03\n\nLogService\x12G\n\x08Register\x12\x1c.log_methods.RegisterRequest\x1a\x1d.log_methods.StandardResponse\x12\x41\n\x05Login\x12\x19.log_methods.LoginRequest\x1a\x1d.log_methods.StandardResponse\x12Q\n\rStoreUserData\x12!.log_methods.StoreUserDataRequest\x1a\x1d.log_methods.StandardResponse\x12Y\n\x11\x43hatbotInitialize\x12%.log_methods.ChatbotInitializeRequest\x1a\x1d.log_methods.StandardResponse\x12M\n\x0b\x43hatbotSend\x12\x1f.log_methods.ChatbotSendRequest\x1a\x1d.log_methods.StandardResponse\x12W\n\x10\x45thicsEngineSend\x12$.log_methods.EthicsEngineSendRequest\x1a\x1d.log_methods.StandardResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anonalog_server.log_methods_pb2.log_methods_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=66
  _globals['_REGISTERREQUEST']._serialized_end=119
  _globals['_LOGINREQUEST']._serialized_start=121
  _globals['_LOGINREQUEST']._serialized_end=171
  _globals['_STOREUSERDATAREQUEST']._serialized_start=173
  _globals['_STOREUSERDATAREQUEST']._serialized_end=254
  _globals['_CHATBOTINITIALIZEREQUEST']._serialized_start=256
  _globals['_CHATBOTINITIALIZEREQUEST']._serialized_end=365
  _globals['_CHATBOTSENDREQUEST']._serialized_start=367
  _globals['_CHATBOTSENDREQUEST']._serialized_end=442
  _globals['_ETHICSENGINESENDREQUEST']._serialized_start=445
  _globals['_ETHICSENGINESENDREQUEST']._serialized_end=586
  _globals['_STANDARDRESPONSE']._serialized_start=588
  _globals['_STANDARDRESPONSE']._serialized_end=640
  _globals['_LOGSERVICE']._serialized_start=643
  _globals['_LOGSERVICE']._serialized_end=1137
# @@protoc_insertion_point(module_scope)
